import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "/admin/dashboard/main",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/submitclaims",
    title: "Submitted Claims",
    moduleName: "submitclaims",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/inprocess",
    title: "In-Process",
    moduleName: "inprocess",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/complete",
    title: "Complete",
    moduleName: "complete",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/statusworkbasket",
    title: "Status Workbasket",
    moduleName: "statusworkbasket",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },

  {
    path: "/admin/dashboard/report",
    title: "Report",
    moduleName: "report",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    role: ["Admin", "Doctor"],
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "MENUITEMS.DASHBOARD.TEXT",
  //   moduleName: "dashboard",
  //   iconType: "material-icons-two-tone",
  //   icon: "space_dashboard",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [
  //     {
  //       path: "/admin/dashboard/main",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
  //       moduleName: "dashboard",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/dashboard/dashboard2",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD2",
  //       moduleName: "dashboard",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },
];
